# Generated by Django 4.0.3 on 2022-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Eevnt Name')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('target_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Target')),
                ('schedule_daytime', models.DateTimeField(verbose_name='Schedule')),
                ('preparation_daytime', models.DateTimeField(blank=True, null=True, verbose_name='Preparation')),
                ('implementation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Implemantation')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark')),
            ],
        ),
    ]
