# Generated by Django 4.0.3 on 2022-04-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='detail_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Remark'),
        ),
    ]
