# Generated by Django 4.0.4 on 2022-04-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSchedule', '0002_eventschedule_detail_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='event_name',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
    ]
