# Generated by Django 4.0.3 on 2022-04-11 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y', validators=[django.core.validators.FileExtensionValidator('pdf')], verbose_name='Document File'),
        ),
    ]
