# Generated by Django 4.0.3 on 2022-05-09 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_document_remarks_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Document File'),
        ),
    ]
