# Generated by Django 4.0.3 on 2022-05-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CirculationBoard', '0004_remove_circulationboard_document_list'),
        ('Documents', '0004_alter_document_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='circulation_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CirculationBoard.circulationboard'),
        ),
    ]
