# Generated by Django 4.0.3 on 2022-04-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
        ('CirculationBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cirsulationboard',
            new_name='Circulationboard',
        ),
    ]
