# Generated by Django 4.0.3 on 2022-05-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CirculationBoard', '0003_alter_circulationboard_document_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulationboard',
            name='document_list',
        ),
    ]
